### ISSUE TITLE
Stylus/Sass/Less

### ISSUE THREAD

**Issue by martinsbicudo** [PolymerX/lit-loader#2]
How can i use Stylus/Sass/Less with single template?

**Comment by LasaleFamine** [comment]
Hi @martinsbicudo, other compilers for CSS are not supported because I thought PostCSS is the most versatile out there. 
You can use PostCSS plugins for working with Stylus/Sass/Less. Something like https://github.com/seaneking/poststylus or https://github.com/postcss/postcss-scss should work for you.

**Comment by equinusocio** [comment]
Please note that these plugins doesn't allow you to access all the features of the respective preprocessor. Working with components you don't really need a preprocessor since every piece have his own code. You may need mixins, functions and loops (maybe)...nothing you can't get with postcss keeping things simple.
